import type { MerchantMetricRecord } from './types'

export const mockOlapRecords: MerchantMetricRecord[] = [
  // 核心测试数据 (前 12 条与任务强关联)
  {
    id: 'M-101',
    merchantName: '星澜极客数码专卖',
    category: '3C数码',
    subCategory: '音频穿戴',
    channel: '线上自营',
    region: '华东',
    orderCount: 1420,
    gmv: 1263800,
    returnRate: 15.8,
    complaints: 6,
    grossMargin: 38.5,
    topRiskSku: '星澜降噪无线耳机 Pro (批次A)',
  },
  {
    id: 'M-102',
    merchantName: '超能声学官方旗舰',
    category: '3C数码',
    subCategory: '电竞外设',
    channel: '线上自营',
    region: '华北',
    orderCount: 980,
    gmv: 1254400,
    returnRate: 16.5,
    complaints: 5,
    grossMargin: 42.0,
    topRiskSku: '7.1声道环绕电竞声卡适配器',
  },
  {
    id: 'M-103',
    merchantName: '简物生活居家馆',
    category: '家居日用',
    subCategory: '寝居家纺',
    channel: '线上自营',
    region: '华东',
    orderCount: 2150,
    gmv: 1333000,
    returnRate: 11.8,
    complaints: 4,
    grossMargin: 52.0,
    topRiskSku: '记忆海绵多功能护颈慢回弹枕',
  },
  {
    id: 'M-104',
    merchantName: '云端潮履精选店',
    category: '服饰箱包',
    subCategory: '运动鞋履',
    channel: '线上自营',
    region: '华南',
    orderCount: 1840,
    gmv: 1380000,
    returnRate: 19.2,
    complaints: 7,
    grossMargin: 55.4,
    topRiskSku: '透气减震复古碳板厚底跑鞋',
  },
  {
    id: 'M-105',
    merchantName: '禾下鲜品绿色自营',
    category: '食品生鲜',
    subCategory: '坚果炒货',
    channel: '线上自营',
    region: '华东',
    orderCount: 3200,
    gmv: 1696000,
    returnRate: 8.2,
    complaints: 1,
    grossMargin: 28.0,
    topRiskSku: '临安有机手剥山核桃仁罐装',
  },
  {
    id: 'M-106',
    merchantName: '未来视界数码体验',
    category: '3C数码',
    subCategory: '智能显示',
    channel: '线上自营',
    region: '华北',
    orderCount: 890,
    gmv: 854400,
    returnRate: 13.5,
    complaints: 4,
    grossMargin: 35.0,
    topRiskSku: '4K超清便携OLED色彩校正拓展屏',
  },
  {
    id: 'M-107',
    merchantName: '风尚服饰直营旗舰',
    category: '服饰箱包',
    subCategory: '户外服饰',
    channel: '线上自营',
    region: '华东',
    orderCount: 1650,
    gmv: 1468500,
    returnRate: 17.8,
    complaints: 5,
    grossMargin: 58.2,
    topRiskSku: '三合一压胶防暴雨户外冲锋衣',
  },
  {
    id: 'M-108',
    merchantName: '华东线下加盟数码体验中心',
    category: '3C数码',
    subCategory: '智能配件',
    channel: '线下加盟',
    region: '华东',
    orderCount: 2800,
    gmv: 1820000,
    returnRate: 4.8,
    complaints: 1,
    grossMargin: 24.5,
    topRiskSku: 'GaN 65W 三口氮化镓快充头',
  },
  {
    id: 'M-109',
    merchantName: '环球数码跨境直通',
    category: '3C数码',
    subCategory: '客制化外设',
    channel: '跨境专区',
    region: '华南',
    orderCount: 650,
    gmv: 942500,
    returnRate: 14.8,
    complaints: 3,
    grossMargin: 46.0,
    topRiskSku: '全CNC铝坨坨客制化机械键盘',
  },
  {
    id: 'M-110',
    merchantName: '轻享乐活家居小铺',
    category: '家居日用',
    subCategory: '餐厨卫浴',
    channel: '线上自营',
    region: '华东',
    orderCount: 1400,
    gmv: 448000,
    returnRate: 5.2,
    complaints: 0,
    grossMargin: 48.0,
    topRiskSku: '食品级硅胶折叠加厚沥水架',
  },
  {
    id: 'M-111',
    merchantName: '自然美味休闲零食',
    category: '食品生鲜',
    subCategory: '冻干果品',
    channel: '线上自营',
    region: '华南',
    orderCount: 4200,
    gmv: 882000,
    returnRate: 3.5,
    complaints: 0,
    grossMargin: 32.0,
    topRiskSku: '冻干原切香脆白巧克力草莓',
  },
  {
    id: 'M-112',
    merchantName: '清爽净界美妆精选',
    category: '美妆个护',
    subCategory: '面部护肤',
    channel: '线上自营',
    region: '华东',
    orderCount: 1980,
    gmv: 1188000,
    returnRate: 11.2,
    complaints: 3,
    grossMargin: 64.0,
    topRiskSku: '积雪草舒缓修护高保湿精华液',
  },
  // 扩充至 104 条真实规模数据集
  ...Array.from({ length: 92 }, (_, i) => {
    const idx = i + 13
    const cats: MerchantMetricRecord['category'][] = [
      '3C数码',
      '家居日用',
      '服饰箱包',
      '食品生鲜',
      '美妆个护',
    ]
    const channels: MerchantMetricRecord['channel'][] = ['线上自营', '线下加盟', '跨境专区']
    const regions: MerchantMetricRecord['region'][] = ['华东', '华南', '华北', '西南']
    const cat = cats[idx % cats.length]
    const channel = channels[idx % channels.length]
    const region = regions[idx % regions.length]
    const avgOrderPrice = 180 + (idx * 37) % 750
    const orderCount = 500 + (idx * 63) % 2500
    const returnRate = Math.round((4.0 + ((idx * 13) % 160) / 10) * 10) / 10
    const complaints = (idx * 7) % 8

    return {
      id: `M-${100 + idx}`,
      merchantName: `星澜商业伙伴-${cat}分店#${idx}`,
      category: cat,
      subCategory: `${cat}通用衍生子类`,
      channel,
      region,
      orderCount,
      gmv: orderCount * avgOrderPrice,
      returnRate,
      complaints,
      grossMargin: 20 + (idx * 11) % 45,
      topRiskSku: `${cat}高频退货诊断款式批次-${idx}`,
    }
  }),
]
