import type { EnvConfigItem, MicroService, PodInstance, TerminalLog } from './types'

export const initialServices: MicroService[] = [
  {
    id: 'svc-payment',
    name: 'payment-service',
    namespace: 'prod-core',
    currentVersion: 'v2.3.0',
    targetVersion: 'v2.4.0',
    status: 'healthy',
    replicas: 3,
    readyReplicas: 3,
    cpuUsage: 34,
    memoryUsage: 1420,
    lastDeployed: '2026-09-01 14:22:00',
    trafficWeight: 10,
  },
  {
    id: 'svc-gateway',
    name: 'api-gateway',
    namespace: 'prod-core',
    currentVersion: 'v3.2.1',
    targetVersion: 'v3.2.1',
    status: 'healthy',
    replicas: 4,
    readyReplicas: 4,
    cpuUsage: 48,
    memoryUsage: 2180,
    lastDeployed: '2026-08-28 10:00:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-auth',
    name: 'auth-service',
    namespace: 'prod-core',
    currentVersion: 'v2.1.0',
    targetVersion: 'v2.1.0',
    status: 'healthy',
    replicas: 3,
    readyReplicas: 3,
    cpuUsage: 22,
    memoryUsage: 980,
    lastDeployed: '2026-08-30 18:40:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-settlement',
    name: 'settlement-service',
    namespace: 'prod-core',
    currentVersion: 'v2.0.1',
    targetVersion: 'v2.0.1',
    status: 'healthy',
    replicas: 2,
    readyReplicas: 2,
    cpuUsage: 15,
    memoryUsage: 760,
    lastDeployed: '2026-08-25 09:12:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-inventory',
    name: 'inventory-service',
    namespace: 'prod-core',
    currentVersion: 'v2.5.2',
    targetVersion: 'v2.5.2',
    status: 'healthy',
    replicas: 3,
    readyReplicas: 3,
    cpuUsage: 41,
    memoryUsage: 1650,
    lastDeployed: '2026-08-29 11:20:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-risk',
    name: 'risk-control-service',
    namespace: 'prod-core',
    currentVersion: 'v2.8.1',
    targetVersion: 'v2.8.1',
    status: 'healthy',
    replicas: 2,
    readyReplicas: 2,
    cpuUsage: 55,
    memoryUsage: 2400,
    lastDeployed: '2026-09-02 16:00:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-user',
    name: 'user-profile-service',
    namespace: 'prod-biz',
    currentVersion: 'v1.9.4',
    targetVersion: 'v1.9.4',
    status: 'healthy',
    replicas: 3,
    readyReplicas: 3,
    cpuUsage: 28,
    memoryUsage: 1120,
    lastDeployed: '2026-08-20 15:30:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-order',
    name: 'order-service',
    namespace: 'prod-biz',
    currentVersion: 'v4.1.0',
    targetVersion: 'v4.1.0',
    status: 'healthy',
    replicas: 4,
    readyReplicas: 4,
    cpuUsage: 62,
    memoryUsage: 3100,
    lastDeployed: '2026-09-03 12:10:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-cart',
    name: 'cart-service',
    namespace: 'prod-biz',
    currentVersion: 'v2.2.0',
    targetVersion: 'v2.2.0',
    status: 'healthy',
    replicas: 2,
    readyReplicas: 2,
    cpuUsage: 18,
    memoryUsage: 820,
    lastDeployed: '2026-08-19 14:00:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-product',
    name: 'product-catalog-service',
    namespace: 'prod-biz',
    currentVersion: 'v3.0.5',
    targetVersion: 'v3.0.5',
    status: 'healthy',
    replicas: 3,
    readyReplicas: 3,
    cpuUsage: 32,
    memoryUsage: 1450,
    lastDeployed: '2026-08-27 17:15:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-logistics',
    name: 'logistics-dispatch-service',
    namespace: 'prod-biz',
    currentVersion: 'v1.8.0',
    targetVersion: 'v1.8.0',
    status: 'healthy',
    replicas: 2,
    readyReplicas: 2,
    cpuUsage: 20,
    memoryUsage: 910,
    lastDeployed: '2026-08-22 10:45:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-search',
    name: 'search-indexer-service',
    namespace: 'prod-biz',
    currentVersion: 'v3.3.0',
    targetVersion: 'v3.3.0',
    status: 'healthy',
    replicas: 3,
    readyReplicas: 3,
    cpuUsage: 52,
    memoryUsage: 2850,
    lastDeployed: '2026-08-24 16:30:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-recommend',
    name: 'recommendation-service',
    namespace: 'prod-biz',
    currentVersion: 'v1.7.2',
    targetVersion: 'v1.7.2',
    status: 'healthy',
    replicas: 2,
    readyReplicas: 2,
    cpuUsage: 68,
    memoryUsage: 3400,
    lastDeployed: '2026-08-26 11:00:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-notification',
    name: 'notification-service',
    namespace: 'infra',
    currentVersion: 'v2.4.0',
    targetVersion: 'v2.4.0',
    status: 'healthy',
    replicas: 2,
    readyReplicas: 2,
    cpuUsage: 12,
    memoryUsage: 640,
    lastDeployed: '2026-08-15 09:20:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-analytics',
    name: 'data-analytics-worker',
    namespace: 'infra',
    currentVersion: 'v1.4.0',
    targetVersion: 'v1.4.0',
    status: 'healthy',
    replicas: 2,
    readyReplicas: 2,
    cpuUsage: 74,
    memoryUsage: 4100,
    lastDeployed: '2026-08-18 14:10:00',
    trafficWeight: 100,
  },
  {
    id: 'svc-logger',
    name: 'audit-logger-service',
    namespace: 'infra',
    currentVersion: 'v2.0.0',
    targetVersion: 'v2.0.0',
    status: 'healthy',
    replicas: 2,
    readyReplicas: 2,
    cpuUsage: 16,
    memoryUsage: 710,
    lastDeployed: '2026-08-16 11:30:00',
    trafficWeight: 100,
  },
]

export const initialEnvConfigs: EnvConfigItem[] = [
  { key: 'PORT', value: '8080', description: '服务监听端口', isSecret: false },
  { key: 'SPRING_PROFILES_ACTIVE', value: 'production', description: 'Spring 运行环境配置', isSecret: false },
  { key: 'DATABASE_URL', value: 'jdbc:postgresql://db-pg-cluster.internal:5432/pay_prod', description: '主库 PostgreSQL 数据库连接串', isSecret: true },
  { key: 'DATABASE_MAX_POOL_SIZE', value: '30', description: 'HikariCP 最大数据库连接池容量', isSecret: false },
  { key: 'KAFKA_BOOTSTRAP_SERVERS', value: 'kafka-broker-01.internal:9092,kafka-broker-02.internal:9092', description: 'Kafka 消息中间件集群地址', isSecret: false },
  { key: 'KAFKA_TOPIC_PAYMENT_EVENTS', value: 'topic.prod.payment.transaction-events.v1', description: '支付交易事件广播主题', isSecret: false },
  { key: 'CIRCUIT_BREAKER_FAILURE_RATE', value: '50', description: 'Resilience4j 熔断器异常率阈值 (%)', isSecret: false },
  { key: 'LOG_LEVEL', value: 'INFO', description: '生产根日志记录级别', isSecret: false },
  { key: 'METRICS_PROMETHEUS_ENABLED', value: 'true', description: 'Prometheus 监控指标抓取开关', isSecret: false },
  { key: 'OPENTELEMETRY_EXPORTER_ENDPOINT', value: 'http://otel-collector.infra:4317', description: 'OTel 追踪链路采集器上报端点', isSecret: false },
  { key: 'PAYMENT_IDEMPOTENT_TTL_SECONDS', value: '7200', description: '支付幂等防重 Token 缓存 TTL', isSecret: false },
  { key: 'SECURITY_TOKEN_ENCRYPTION_KEY', value: 'enc-k8s-sec-7f9a2b1c8e00192a', description: 'AES 资金报文加密密钥', isSecret: true },
]

export const samplePods: PodInstance[] = [
  {
    name: 'payment-service-7f8d9b-x92zk',
    namespace: 'prod-core',
    status: 'Running',
    ready: true,
    restarts: 0,
    node: 'node-cn-hangzhou-k8s-04',
    ip: '10.244.3.11',
    startTime: '2026-09-08 10:14:22',
  },
  {
    name: 'payment-service-7f8d9b-w71lp',
    namespace: 'prod-core',
    status: 'Running',
    ready: true,
    restarts: 0,
    node: 'node-cn-hangzhou-k8s-08',
    ip: '10.244.2.33',
    startTime: '2026-09-08 10:14:25',
  },
  {
    name: 'payment-service-7f8d9b-z55yt',
    namespace: 'prod-core',
    status: 'Running',
    ready: true,
    restarts: 0,
    node: 'node-cn-hangzhou-k8s-12',
    ip: '10.244.4.88',
    startTime: '2026-09-08 10:14:29',
  },
]

export const baseTerminalLogs: TerminalLog[] = [
  {
    timestamp: '10:14:20.102',
    level: 'info',
    podName: 'payment-service-7f8d9b-x92zk',
    traceId: 'trace-89a1c098df23',
    thread: 'main',
    logger: 'com.xinglan.payment.PaymentApplication',
    message: 'Starting PaymentApplication v2.3.0 using Java 21.0.4 with PID 1',
  },
  {
    timestamp: '10:14:21.450',
    level: 'info',
    podName: 'payment-service-7f8d9b-x92zk',
    traceId: 'trace-89a1c098df23',
    thread: 'main',
    logger: 'com.zaxxer.hikari.HikariDataSource',
    message: 'HikariPool-1 - Starting... connection pool established (max: 30)',
  },
  {
    timestamp: '10:14:22.890',
    level: 'info',
    podName: 'payment-service-7f8d9b-x92zk',
    traceId: 'trace-89a1c098df23',
    thread: 'main',
    logger: 'org.springframework.boot.web.embedded.tomcat.TomcatWebServer',
    message: 'Tomcat initialized with port 8080 (http)',
  },
  {
    timestamp: '10:14:23.010',
    level: 'info',
    podName: 'payment-service-7f8d9b-w71lp',
    traceId: 'trace-90b2d119ef44',
    thread: 'main',
    logger: 'com.xinglan.payment.config.KafkaConsumerConfig',
    message: 'Subscribed to topic: topic.prod.payment.transaction-events.v1 (group: payment-settle-group)',
  },
  {
    timestamp: '10:14:25.660',
    level: 'info',
    podName: 'payment-service-7f8d9b-z55yt',
    traceId: 'trace-91c3e220fa55',
    thread: 'grpc-nio-worker-2',
    logger: 'com.xinglan.payment.service.ChannelRouter',
    message: 'Payment channel health probe OK: ALIPAY_DIRECT (latency: 14ms), WECHAT_PAY (latency: 19ms)',
  },
]
