import type { KanbanColumn } from './types'

export const initialKanbanColumns: KanbanColumn[] = [
  {
    id: 'backlog',
    title: '规划',
    cards: [
      {
        id: 'TASK-1011',
        title: '多语言包自动化提取流水线',
        epic: '国际化出海',
        assignee: '陈工',
        priority: 'P2-中',
        storyPoints: 5,
        completedSubtasks: 1,
        totalSubtasks: 4,
        tags: ['基建', 'i18n'],
        dependencies: [],
        description: '自动化扫描 AST 提取中英日多语言字典。',
      },
      {
        id: 'TASK-1012',
        title: '移动端手势轻扫响应优化',
        epic: '用户体验',
        assignee: '张工',
        priority: 'P3-低',
        storyPoints: 2,
        completedSubtasks: 0,
        totalSubtasks: 3,
        tags: ['体验', 'UI'],
        dependencies: [],
        description: '在移动端视口下增加轻扫关闭抽屉与平滑动效。',
      },
      {
        id: 'TASK-1015',
        title: 'GraphQL 网关字段级权限切面',
        epic: '基础设施',
        assignee: '王工',
        priority: 'P1-高',
        storyPoints: 8,
        completedSubtasks: 2,
        totalSubtasks: 6,
        tags: ['网关', '安全'],
        dependencies: [],
        description: '基于 RBAC 对 GraphQL 解析器实施字段级细粒度权限校验。',
      },
      {
        id: 'TASK-1018',
        title: '用户行为埋点离线清洗 ETL',
        epic: '核心改造',
        assignee: '李工',
        priority: 'P2-中',
        storyPoints: 5,
        completedSubtasks: 1,
        totalSubtasks: 3,
        tags: ['数据', 'ETL'],
        dependencies: [],
        description: 'Spark 日志清洗任务调优，去重率提升 15%。',
      },
      {
        id: 'TASK-1019',
        title: '企业微信机器人告警卡片交互',
        epic: '基础设施',
        assignee: '张工',
        priority: 'P3-低',
        storyPoints: 3,
        completedSubtasks: 0,
        totalSubtasks: 2,
        tags: ['监控', '告警'],
        dependencies: [],
        description: '告警群支持点击卡片一键认领与静音 30 分钟。',
      },
      {
        id: 'TASK-1022',
        title: '无障碍屏幕阅读器兼容改造 (ARIA)',
        epic: '用户体验',
        assignee: '陈工',
        priority: 'P2-中',
        storyPoints: 5,
        completedSubtasks: 1,
        totalSubtasks: 5,
        tags: ['无障碍', '合规'],
        dependencies: [],
        description: '补全全站 aria-live 与 aria-expanded 属性。',
      },
      {
        id: 'TASK-1024',
        title: '海外 Stripe 信用卡 3DS 验证',
        epic: '国际化出海',
        assignee: '林工',
        priority: 'P1-高',
        storyPoints: 8,
        completedSubtasks: 0,
        totalSubtasks: 4,
        tags: ['支付', '出海'],
        dependencies: ['TASK-1082'],
        description: '对接欧洲 SCA 强客户身份验证标准。',
      },
    ],
  },
  {
    id: 'in_progress',
    title: '开发中',
    cards: [
      {
        id: 'TASK-1082',
        title: '结算中心重构',
        epic: '核心改造',
        assignee: '林工',
        priority: 'P0-紧急',
        storyPoints: 8,
        completedSubtasks: 4,
        totalSubtasks: 5,
        tags: ['支付', '核心改造'],
        dependencies: [],
        description: '拆分订单状态机与结算通道，引入双重校验防超卖与掉单。',
      },
      {
        id: 'TASK-1055',
        title: '消息推送通道降级容灾方案',
        epic: '基础设施',
        assignee: '王工',
        priority: 'P1-高',
        storyPoints: 5,
        completedSubtasks: 2,
        totalSubtasks: 4,
        tags: ['高可用', '架构'],
        dependencies: ['TASK-1011'],
        description: '主通道延迟超过 2s 时自动降级至备用长连接通道。',
      },
      {
        id: 'TASK-1060',
        title: '用户增长同期群漏斗图表 v2',
        epic: '用户体验',
        assignee: '陈工',
        priority: 'P2-中',
        storyPoints: 3,
        completedSubtasks: 2,
        totalSubtasks: 3,
        tags: ['BI', '可视化'],
        dependencies: [],
        description: '重构 Chart.js 响应式画布，支持拖选时间窗口。',
      },
      {
        id: 'TASK-1064',
        title: 'Redis 哨兵集群平滑扩缩容方案',
        epic: '基础设施',
        assignee: '王工',
        priority: 'P1-高',
        storyPoints: 5,
        completedSubtasks: 3,
        totalSubtasks: 4,
        tags: ['存储', 'DBA'],
        dependencies: [],
        description: '实现在线迁移分片槽位，业务零感知。',
      },
      {
        id: 'TASK-1068',
        title: '商品详情页首屏 LCP 性能优化',
        epic: '用户体验',
        assignee: '张工',
        priority: 'P2-中',
        storyPoints: 3,
        completedSubtasks: 1,
        totalSubtasks: 3,
        tags: ['性能', '前端'],
        dependencies: [],
        description: '采用骨架屏预渲染与关键 CSS 提取，LCP < 1.2s。',
      },
      {
        id: 'TASK-1070',
        title: '多币种汇率定时同步调度服务',
        epic: '国际化出海',
        assignee: '林工',
        priority: 'P2-中',
        storyPoints: 5,
        completedSubtasks: 2,
        totalSubtasks: 4,
        tags: ['出海', '汇率'],
        dependencies: [],
        description: '对接欧洲央行与中国银行外汇牌价定时抓取。',
      },
      {
        id: 'TASK-1072',
        title: '全链路分布式 TraceID 染色机制',
        epic: '基础设施',
        assignee: '王工',
        priority: 'P1-高',
        storyPoints: 5,
        completedSubtasks: 3,
        totalSubtasks: 5,
        tags: ['网关', '可观测'],
        dependencies: [],
        description: '网关层透传 baggage 标头，支撑全链路调用树展示。',
      },
    ],
  },
  {
    id: 'testing',
    title: '联调',
    cards: [
      {
        id: 'TASK-1033',
        title: '开放平台 OAuth2.1 认证中间件',
        epic: '基础设施',
        assignee: '林工',
        priority: 'P1-高',
        storyPoints: 5,
        completedSubtasks: 4,
        totalSubtasks: 5,
        tags: ['安全', '网关'],
        dependencies: [],
        description: '支持 PKCE 认证码增强流程与 JWT 动态验签。',
      },
      {
        id: 'TASK-1040',
        title: '全文搜索 ElasticSearch 并发压测',
        epic: '核心改造',
        assignee: '张工',
        priority: 'P2-中',
        storyPoints: 5,
        completedSubtasks: 3,
        totalSubtasks: 4,
        tags: ['测试', '性能'],
        dependencies: [],
        description: '压测千万级商品关键词召回 P99 耗时控制在 50ms 内。',
      },
      {
        id: 'TASK-1044',
        title: '智能客服工单路由分流压测',
        epic: '用户体验',
        assignee: '陈工',
        priority: 'P2-中',
        storyPoints: 3,
        completedSubtasks: 2,
        totalSubtasks: 3,
        tags: ['客服', '风控'],
        dependencies: [],
        description: '按客服坐席负载动态分发 500+ 并发会话。',
      },
      {
        id: 'TASK-1048',
        title: '电子合同在线手写签名组件验收',
        epic: '核心改造',
        assignee: '李工',
        priority: 'P2-中',
        storyPoints: 3,
        completedSubtasks: 3,
        totalSubtasks: 3,
        tags: ['法务', '前端'],
        dependencies: [],
        description: '支持 Canvas 平滑压感笔触与哈希防篡改存证。',
      },
      {
        id: 'TASK-1050',
        title: '海外 CDN 节点加速可用性巡检',
        epic: '国际化出海',
        assignee: '王工',
        priority: 'P2-中',
        storyPoints: 3,
        completedSubtasks: 2,
        totalSubtasks: 3,
        tags: ['网络', 'CDN'],
        dependencies: [],
        description: '针对北美及东南亚各 PoP 节点进行 Ping 探针巡检。',
      },
      {
        id: 'TASK-1052',
        title: '防刷单风控规则引擎黑名单验证',
        epic: '核心改造',
        assignee: '林工',
        priority: 'P1-高',
        storyPoints: 5,
        completedSubtasks: 4,
        totalSubtasks: 4,
        tags: ['风控', '合规'],
        dependencies: [],
        description: '识别批量虚拟设备指纹与秒级高频下单异常。',
      },
    ],
  },
  {
    id: 'acceptance',
    title: '待验收',
    cards: [
      {
        id: 'TASK-1020',
        title: '暗黑模式主题色彩无障碍验收',
        epic: '用户体验',
        assignee: '王工',
        priority: 'P2-中',
        storyPoints: 3,
        completedSubtasks: 3,
        totalSubtasks: 3,
        tags: ['设计系统', 'UI'],
        dependencies: [],
        description: '对齐 Design Token 对比度标准，满足 WCAG 2.1 AA 级。',
      },
      {
        id: 'TASK-1025',
        title: '文件断点续传与秒传组件接入',
        epic: '基础设施',
        assignee: '陈工',
        priority: 'P1-高',
        storyPoints: 5,
        completedSubtasks: 4,
        totalSubtasks: 4,
        tags: ['存储', '网络'],
        dependencies: [],
        description: '支持 5GB 大文件分片上传与 SHA256 秒传复用。',
      },
      {
        id: 'TASK-1028',
        title: '供应商入驻资质三类认证审批流',
        epic: '核心改造',
        assignee: '李工',
        priority: 'P2-中',
        storyPoints: 3,
        completedSubtasks: 3,
        totalSubtasks: 3,
        tags: ['B2B', '入驻'],
        dependencies: [],
        description: '打通企查查天眼查工商资质自动联网比对。',
      },
      {
        id: 'TASK-1030',
        title: '数据大屏 3D 地球航线动效落地',
        epic: '用户体验',
        assignee: '张工',
        priority: 'P3-低',
        storyPoints: 3,
        completedSubtasks: 3,
        totalSubtasks: 3,
        tags: ['Three.js', '大屏'],
        dependencies: [],
        description: '基于 Three.js 绘制全球实时跨境订单物流飞线。',
      },
      {
        id: 'TASK-1032',
        title: '新加坡可用区多活热备切换演练',
        epic: '国际化出海',
        assignee: '林工',
        priority: 'P0-紧急',
        storyPoints: 8,
        completedSubtasks: 6,
        totalSubtasks: 6,
        tags: ['容灾', '高可用'],
        dependencies: [],
        description: '模拟单可用区掉电，流量在 30 秒内无损切换至备份区。',
      },
    ],
  },
  {
    id: 'released',
    title: '已发布',
    cards: [
      {
        id: 'TASK-0980',
        title: '星澜工作台 v2.4.0 脚手架初始化',
        epic: '基础设施',
        assignee: '林工',
        priority: 'P0-紧急',
        storyPoints: 8,
        completedSubtasks: 5,
        totalSubtasks: 5,
        tags: ['架构', '核心'],
        dependencies: [],
        description: '完成 Vite 模块化升级与微前端沙箱配置。',
      },
      {
        id: 'TASK-0995',
        title: '用户行为日志脱敏合规改造',
        epic: '核心改造',
        assignee: '张工',
        priority: 'P1-高',
        storyPoints: 5,
        completedSubtasks: 4,
        totalSubtasks: 4,
        tags: ['合规', '安全'],
        dependencies: [],
        description: '手机号身份证进行 SHA256 掩码与加密脱敏。',
      },
      {
        id: 'TASK-0998',
        title: '短信验证码服务供应商动态容灾',
        epic: '基础设施',
        assignee: '王工',
        priority: 'P2-中',
        storyPoints: 3,
        completedSubtasks: 3,
        totalSubtasks: 3,
        tags: ['通信', '高可用'],
        dependencies: [],
        description: '阿里云与腾讯云短信通道按到达率 5 分钟自动切换。',
      },
      {
        id: 'TASK-1002',
        title: '企业微信通知工作流应用开通',
        epic: '用户体验',
        assignee: '陈工',
        priority: 'P3-低',
        storyPoints: 2,
        completedSubtasks: 2,
        totalSubtasks: 2,
        tags: ['协同', '通知'],
        dependencies: [],
        description: '支持审批结果一键推送到企业微信待办。',
      },
      {
        id: 'TASK-1005',
        title: '跨境海关报关报检标准接口对接',
        epic: '国际化出海',
        assignee: '林工',
        priority: 'P1-高',
        storyPoints: 8,
        completedSubtasks: 6,
        totalSubtasks: 6,
        tags: ['海关', '出海'],
        dependencies: [],
        description: '完成电子口岸统一版三单比对报文直连。',
      },
      {
        id: 'TASK-1008',
        title: '全站 CDN 静态资源 Brotli 压缩开启',
        epic: '基础设施',
        assignee: '张工',
        priority: 'P3-低',
        storyPoints: 2,
        completedSubtasks: 2,
        totalSubtasks: 2,
        tags: ['性能', 'CDN'],
        dependencies: [],
        description: '相比 Gzip 传输体积进一步缩减 18%。',
      },
    ],
  },
]
